export const DefaultValues = {
  name: "",
  middleName: "",
  lastName: "",
  startDay: null,
  startMonth: null,
  startYear: null,
  email: "",
  mobile: "",
  address: "",
  hoursPerWeek: 1,
  isOngoing: false,
  contractType: "permanent",
  workType: "full-time",
  finishDay: null,
  finishMonth: null,
  finishYear: null,
};
