export const DefaultValues = {
  name: "",
  middleName: "",
  lastName: "",
  startDay: 28,
  startMonth: 7,
  startYear: 2021,
  email: "",
  mobile: "",
  address: "",
  hoursPerWeek: 1,
  isOngoing: false,
  contractType: "contract",
  workType: "part-time",
  finishDay: 28,
  finishMonth: 7,
  finishYear: 2021,
};
