export const DefaultValues = {
  name: "",
  middleName: "",
  lastName: "",
  startDay: "28",
  startMonth: "07",
  startYear: "2021",
  startDate: "2021-07-28",
  email: "",
  mobile: "",
  address: "",
  hoursPerWeek: 1,
  isOngoing: false,
  contractType: "contract",
  workType: "part-time",
  finishDay: "28",
  finishMonth: "07",
  finishYear: "2021",
  finishDate: "2021-07-28",
};
